### ISSUE TITLE
Coleções em destaque Component

### ISSUE THREAD

**Issue by gleidsonteixeira** [dcTeam15/Drip-Store#12]
Neste componente cada link deve direcionar para a pagina de produtos com a categoria em questão selecionada

![image](https://github.com/dcTeam15/Drip-Store/assets/8497298/277945e7-1871-42fa-9663-fef27efc7868)

**Comment by LucasDCoelho** [comment]
Task realizada com sucesso. Devido ao horário não estarei dando merge, pois pode ocasionar em erros
